import React, {useState} from 'react';
import {SafeAreaView, View, Text, TextInput, Pressable, ScrollView, StyleSheet, Alert} from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import {StatusBar} from 'expo-status-bar';

const teal='#0f766e', pale='#e6fffb';
const services=[['🧱','Artisans','Trouvez un professionnel fiable'],['👷','Manœuvres','Des équipes pour vos chantiers'],['🔧','Techniciens BTP','Génie civil et topographie'],['🏢','Sociétés BTP','Réalisez vos projets'],['🚚','Transporteurs','Matériaux et équipements'],['🚜','Conducteurs d’engins','Tous les engins BTP'],['🧰','Matériaux et équipements','Achetez près du chantier'],['🏗️','Engins de chantier','À louer et à vendre'],['📍','Terrains','Avec documents de propriété'],['🏠','Immobilier','Maisons, immeubles, bureaux'],['🛋️','Logement express','Villas courte durée']];
const people=['BTP Solutions','Kossi Construction','Quincaillerie Togo','Afi Immobilier','Transport Express','Génie Civil Plus'];

export default function App(){const [screen,setScreen]=useState('home');const [selected,setSelected]=useState('');const [person,setPerson]=useState('');const [message,setMessage]=useState('');const [messages,setMessages]=useState(['Bonjour, comment pouvons-nous vous aider ?']);const [balance,setBalance]=useState(125000);const [images,setImages]=useState([]);
 const open=(s,data={})=>{if(data.service)setSelected(data.service);if(data.person)setPerson(data.person);setScreen(s)};
 const back=()=>setScreen('home');
 const send=()=>{if(message.trim()){setMessages([...messages,message.trim()]);setMessage('')}};
 const pickImages=async()=>{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,selectionLimit:4});if(!r.canceled)setImages(r.assets.slice(0,4))};
 const header=(title)=><View style={styles.header}><Pressable onPress={back}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.headerTitle}>{title}</Text></View>;
 const nav=<View style={styles.nav}>{[['home','⌂','Accueil'],['messages','💬','Messages'],['cash','₣','PPC-Cash'],['publish','＋','Publier'],['profile','♙','Profil']].map(([s,i,t])=><Pressable key={s} style={styles.navItem} onPress={()=>open(s)}><Text style={styles.navIcon}>{i}</Text><Text style={styles.navText}>{t}</Text></Pressable>)}</View>;
 const peopleList=(title)=> <><ScrollView contentContainerStyle={styles.content}>{<Text style={styles.muted}>Prestataires proches de votre position</Text>}{people.map((p,i)=><Pressable style={styles.row} key={p} onPress={()=>open('chat',{person:p})}><View style={styles.avatar}><Text>{p.slice(0,2).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={styles.bold}>{p}</Text><Text style={styles.muted}>{(i+1)*1.3} km · Disponible</Text></View><Text style={styles.link}>Voir</Text></Pressable>)}</ScrollView></>;
 const serviceScreen=()=>{if(selected==='Conducteurs d’engins')return <Select title="Catégories d’engins" items={['Bulldozer','Pelleteuse','Chargeuse','Grue','Bétonnière','Pompe à béton','Niveleuse','Compacteur']} onDone={()=>open('results')}/>;if(['Matériaux et équipements','Terrains','Immobilier','Logement express'].includes(selected))return <Form title={selected} fields={selected==='Matériaux et équipements'?['Que cherchez-vous ?','Ville','Quartier']:['Ville','Quartier']} onDone={()=>open('results')}/>;return peopleList(selected)};
 const render=()=>{if(screen==='home')return <Home onService={s=>open('service',{service:s})} balance={balance}/>;if(screen==='service')return <>{header(selected)}{serviceScreen()}</>;if(screen==='results')return <>{header(selected||'Résultats')}{peopleList(selected)}</>;if(screen==='messages')return <Messages open={open}/>;if(screen==='chat')return <Chat person={person} messages={messages} value={message} setValue={setMessage} send={send} open={open}/>;if(screen==='attachments')return <Attachments open={open}/>;if(screen==='cash')return <Cash balance={balance} open={open}/>;if(screen==='topup')return <Form title="Recharger PPC-Cash" fields={['Numéro de téléphone','Montant en FCFA']} onDone={()=>{setBalance(balance+5000);Alert.alert('Félicitations','Votre recharge PPC-Cash a réussi.')}}/>;if(screen==='pay')return <Form title="Payer / Transférer" fields={['Scanner le QR code du bénéficiaire','Montant en FCFA']} onDone={()=>Alert.alert('Félicitations','Vous avez payé avec succès !')}/>;if(screen==='withdraw')return <Form title="Retirer de l’argent" fields={['Numéro de téléphone','Montant en FCFA']} onDone={()=>Alert.alert('Félicitations','Votre retrait a été envoyé.')}/>;if(screen==='publish')return <Publish images={images} pick={pickImages}/>;if(screen==='profile')return <Profile open={open}/>;if(screen==='account')return <Form title="Mon compte Artisans Togo" fields={['Numéro de téléphone','Ville','Quartier']} onDone={()=>Alert.alert('Profil sauvegardé')}/>;if(screen==='quote')return <Quote/>;if(screen==='paymentCard')return <PaymentCard/>;return <Home onService={s=>open('service',{service:s})} balance={balance}/>};
 return <SafeAreaView style={styles.safe}><StatusBar style="light"/><View style={{flex:1}}>{render()}</View>{['home','messages','cash','publish','profile'].includes(screen)&&nav}</SafeAreaView>}

function Home({onService,balance}){return <ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Text style={styles.heroSmall}>La plateforme qui vous accompagne</Text><Text style={styles.heroTitle}>Artisans Togo</Text><Text style={styles.heroSmall}>Construisez, achetez et trouvez les bons professionnels.</Text></View><View style={styles.wallet}><Text style={styles.mutedLight}>Votre solde PPC-Cash</Text><Text style={styles.balance}>{balance.toLocaleString('fr-FR')} FCFA</Text></View><Text style={styles.title}>Que recherchez-vous ?</Text>{services.map(([icon,title,sub])=><Pressable key={title} style={styles.card} onPress={()=>onService(title)}><Text style={styles.icon}>{icon}</Text><View><Text style={styles.bold}>{title}</Text><Text style={styles.muted}>{sub}</Text></View></Pressable>)}</ScrollView>}
function Form({title,fields,onDone}){return <><View style={styles.header}><Pressable onPress={()=>{}}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.headerTitle}>{title}</Text></View><ScrollView contentContainerStyle={styles.content}><View style={styles.form}>{fields.map(f=><View key={f}><Text style={styles.label}>{f}</Text><TextInput style={styles.input} placeholder={f}/></View>)}<Pressable style={styles.primary} onPress={onDone}><Text style={styles.primaryText}>Valider</Text></Pressable></View></ScrollView></>}
function Select({title,items,onDone}){return <><View style={styles.header}><Text style={styles.headerTitle}>{title}</Text></View><ScrollView contentContainerStyle={styles.content}><View style={styles.form}>{items.map(x=><Text key={x} style={styles.check}>□  {x}</Text>)}<Pressable style={styles.primary} onPress={onDone}><Text style={styles.primaryText}>Valider</Text></Pressable></View></ScrollView></>}
function Messages({open}){return <><View style={styles.header}><Text style={styles.headerTitle}>Discussions</Text></View><ScrollView contentContainerStyle={styles.content}>{people.slice(0,4).map((p,i)=><Pressable style={styles.row} key={p} onPress={()=>open('chat',{person:p})}><View style={styles.avatar}><Text>{p[0]}</Text></View><View style={{flex:1}}><Text style={styles.bold}>{p}</Text><Text style={styles.muted}>{['Votre devis est prêt.','Merci pour votre demande.','Article disponible.','À bientôt.'][i]}</Text></View><Text style={styles.muted}>{i+1} h</Text></Pressable>)}</ScrollView></>}
function Chat({person,messages,value,setValue,send,open}){return <><View style={styles.header}><Pressable onPress={()=>open('messages')}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.headerTitle}>{person||'Discussion'}</Text></View><ScrollView contentContainerStyle={styles.messages}>{messages.map((m,i)=><View key={i} style={[styles.bubble,i%2?styles.mine:null]}><Text>{m}</Text></View>)}</ScrollView><View style={styles.composer}><Pressable onPress={()=>open('attachments')}><Text style={styles.attach}>📎</Text></Pressable><TextInput style={styles.messageInput} value={value} onChangeText={setValue} placeholder="Écrire un message"/><Pressable style={styles.mic} onPress={send}><Text>{value?'➤':'🎤'}</Text></Pressable></View></>}
function Attachments({open}){return <><View style={styles.header}><Pressable onPress={()=>open('chat')}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.headerTitle}>Ajouter</Text></View><View style={styles.content}>{[['🖼️','Galerie'],['📷','Caméra'],['📍','Localisation'],['📄','Document'],['🧾','Devis'],['₣','Carte PPC-Cash']].map(([i,t])=><Pressable style={styles.card} key={t} onPress={()=>open(t==='Devis'?'quote':t==='Carte PPC-Cash'?'paymentCard':'chat')}><Text style={styles.icon}>{i}</Text><Text style={styles.bold}>{t}</Text></Pressable>)}</View></>}
function Cash({balance,open}){return <><View style={styles.header}><Text style={styles.headerTitle}>PPC-Cash</Text></View><ScrollView contentContainerStyle={styles.content}><View style={styles.wallet}><Text style={styles.mutedLight}>Solde PPC-Cash</Text><Text style={styles.balance}>{balance.toLocaleString('fr-FR')} FCFA</Text></View>{[['↥','Recharger PPC-Cash','topup'],['⇄','Payer / Transférer','pay'],['↧','Retirer de l’argent','withdraw'],['☷','Historique des opérations','messages']].map(([i,t,s])=><Pressable style={styles.card} key={t} onPress={()=>open(s)}><Text style={styles.icon}>{i}</Text><Text style={styles.bold}>{t}</Text></Pressable>)}</ScrollView></>}
function Publish({images,pick}){return <><View style={styles.header}><Text style={styles.headerTitle}>Publier</Text></View><ScrollView contentContainerStyle={styles.content}><View style={styles.form}><Text style={styles.title}>Déposer vos articles ici</Text><Pressable style={styles.upload} onPress={pick}><Text style={styles.plus}>＋</Text><Text>Ajouter jusqu’à 4 images ({images.length}/4)</Text></Pressable>{['Nom','Prix','Description','Ville','Quartier'].map(f=><TextInput style={styles.input} key={f} placeholder={f}/>)}<Pressable style={styles.primary} onPress={()=>Alert.alert('Publication','Article envoyé')}><Text style={styles.primaryText}>Envoyer</Text></Pressable></View></ScrollView></>}
function Profile({open}){return <><View style={styles.header}><Text style={styles.headerTitle}>Profil</Text></View><View style={styles.content}>{[['👤','Mon compte Artisans Togo','account'],['🎁','Parrainage','about'],['ⓘ','À propos d’Artisans Togo','about'],['↪','Déconnexion','home']].map(([i,t,s])=><Pressable style={styles.card} key={t} onPress={()=>open(s)}><Text style={styles.icon}>{i}</Text><Text style={styles.bold}>{t}</Text></Pressable>)}</View></>}
function Quote(){return <><View style={styles.header}><Text style={styles.headerTitle}>Artisans Togo · Devis</Text></View><ScrollView contentContainerStyle={styles.content}><View style={styles.form}>{['Niveau des travaux','Matériaux nécessaires','Main-d’œuvre'].map(f=><TextInput style={styles.input} multiline key={f} placeholder={f}/>) }<Text style={styles.bold}>Total : calculé automatiquement</Text><Pressable style={styles.primary} onPress={()=>Alert.alert('Devis','Devis accepté et envoyé')}><Text style={styles.primaryText}>Accepter le devis</Text></Pressable></View></ScrollView></>}
function PaymentCard(){return <><View style={styles.header}><Text style={styles.headerTitle}>Carte PPC-Cash</Text></View><View style={styles.content}><View style={styles.form}><Text style={styles.bold}>Total à payer : 50 000 FCFA</Text><Text style={styles.qr}>▦{`\n`}QR CODE{`\n`}Valable 05:00</Text><Pressable style={styles.primary} onPress={()=>Alert.alert('PPC-Cash','Carte envoyée dans la discussion')}><Text style={styles.primaryText}>Générer</Text></Pressable></View></View></>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f7f8'},header:{height:64,backgroundColor:teal,flexDirection:'row',alignItems:'center',paddingHorizontal:16},back:{color:'#fff',fontSize:34,width:42},headerTitle:{color:'#fff',fontSize:19,fontWeight:'700'},content:{padding:16,paddingBottom:28},hero:{backgroundColor:teal,borderRadius:22,padding:24,marginBottom:16},heroSmall:{color:'#d5fffa'},heroTitle:{color:'#fff',fontSize:30,fontWeight:'800',marginVertical:8},wallet:{backgroundColor:'#102a43',borderRadius:18,padding:18,marginBottom:18},mutedLight:{color:'#c8d8e8'},balance:{fontSize:25,fontWeight:'800',color:'#fff',marginTop:8},title:{fontSize:20,fontWeight:'800',marginVertical:12},card:{backgroundColor:'#fff',borderRadius:15,padding:16,marginBottom:11,flexDirection:'row',alignItems:'center',gap:14,elevation:1},icon:{fontSize:25,width:38},bold:{fontWeight:'700',fontSize:15},muted:{color:'#64748b',marginTop:4},row:{backgroundColor:'#fff',borderRadius:15,padding:13,marginBottom:10,flexDirection:'row',alignItems:'center',gap:12},avatar:{width:48,height:48,borderRadius:24,backgroundColor:'#ccfbf1',alignItems:'center',justifyContent:'center'},link:{color:teal,fontWeight:'700'},form:{backgroundColor:'#fff',borderRadius:17,padding:18},label:{fontWeight:'700',marginTop:12,marginBottom:6},input:{borderWidth:1,borderColor:'#dbe4e8',borderRadius:10,padding:12,marginBottom:11,minHeight:46},primary:{backgroundColor:teal,borderRadius:11,padding:14,alignItems:'center',marginTop:14},primaryText:{color:'#fff',fontWeight:'800'},check:{padding:14,borderBottomWidth:1,borderBottomColor:'#e2e8f0'},nav:{position:'absolute',bottom:0,left:0,right:0,height:70,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#e2e8f0',flexDirection:'row'},navItem:{flex:1,alignItems:'center',justifyContent:'center'},navIcon:{fontSize:21},navText:{fontSize:10,color:'#64748b'},messages:{padding:16,paddingBottom:100},bubble:{backgroundColor:'#fff',padding:12,borderRadius:17,alignSelf:'flex-start',marginBottom:10,maxWidth:'80%'},mine:{backgroundColor:'#ccfbf1',alignSelf:'flex-end'},composer:{position:'absolute',bottom:0,left:0,right:0,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#e2e8f0',padding:8,flexDirection:'row',alignItems:'center',gap:6},attach:{fontSize:22},messageInput:{flex:1,borderWidth:1,borderColor:'#dbe4e8',borderRadius:22,paddingHorizontal:14,paddingVertical:10},mic:{width:43,height:43,borderRadius:22,backgroundColor:teal,alignItems:'center',justifyContent:'center'},upload:{borderWidth:2,borderStyle:'dashed',borderColor:'#99f6e4',borderRadius:15,alignItems:'center',padding:25,marginBottom:15},plus:{fontSize:42,color:teal},qr:{textAlign:'center',fontSize:25,marginVertical:28,color:teal}}
